version: '3.8'
services:
  db:
    image: 'postgres:12'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=myawesomedb
volumes:
  pgdata: {}
